/*
 * The MIT License
 *
 * Copyright 2013 Andreas Giemza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package de.andreasgiemza.jgeagle.options;

import java.awt.Color;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Andreas Giemza
 */
public class OptionsPanel extends javax.swing.JPanel {

    private final JDialog jDialog;
    private final Options options;

    /**
     * Creates new form OptionsPanel
     *
     * @param jDialog
     * @param options
     */
    public OptionsPanel(JDialog jDialog, Options options) {
        initComponents();

        this.jDialog = jDialog;
        this.options = options;

        loadOptions();
    }

    private void loadOptions() {
        eagleBinaryTextField.setText(options.getPropEagleBinary());
        eagleSchematicBackgroundTextField.setText(options.getPropSchematicBackground());
        eagleSchematicBackgroundPanel.setBackground(Color.decode(options.getPropSchematicBackground()));
        eagleBoardBackgroundTextField.setText(options.getPropBoardBackground());
        eagleBoardBackgroundPanel.setBackground(Color.decode(options.getPropBoardBackground()));
        diffImageSchematicDpiSpinner.setModel(new SpinnerNumberModel(options.getPropSchematicDpiAsInt(), 50, 600, 50));
        diffImageBoardDpiSpinner.setModel(new SpinnerNumberModel(options.getPropBoardDpiAsInt(), 50, 600, 50));
        diffImageUnchangedAlphaSpinner.setModel(new SpinnerNumberModel(options.getPropUnchangedAlphaAsDouble(), 0, 1, 0.01));
        diffImageAddedElementTextField.setText(options.getPropAddedElementColor());
        diffImageAddedElementPanel.setBackground(Color.decode(options.getPropAddedElementColor()));
        diffImageRemovedElementTextField.setText(options.getPropRemovedElementColor());
        diffImageRemovedElementPanel.setBackground(Color.decode(options.getPropRemovedElementColor()));
        diffImageUndefinedTextField.setText(options.getPropUndefinedColor());
        diffImageUndefinedPanel.setBackground(Color.decode(options.getPropUndefinedColor()));
    }

    private void close() {
        jDialog.dispose();
        jDialog.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eagleBinaryFileChooser = new javax.swing.JFileChooser();
        eaglePanel = new javax.swing.JPanel();
        eagleBinaryLabel = new javax.swing.JLabel();
        eagleBinaryTextField = new javax.swing.JTextField();
        eagleBinaryButton = new javax.swing.JButton();
        eagleSchematicBackgroundLabel = new javax.swing.JLabel();
        eagleSchematicBackgroundTextField = new javax.swing.JTextField();
        eagleSchematicBackgroundPanel = new javax.swing.JPanel();
        eagleSchematicBackgroundButton = new javax.swing.JButton();
        eagleBoardBackgroundLabel = new javax.swing.JLabel();
        eagleBoardBackgroundTextField = new javax.swing.JTextField();
        eagleBoardBackgroundPanel = new javax.swing.JPanel();
        eagleBoardBackgroundButton = new javax.swing.JButton();
        diffImagePanel = new javax.swing.JPanel();
        diffImageSchematicDpiSpinner = new javax.swing.JSpinner();
        diffImageBoardDpiLabel = new javax.swing.JLabel();
        diffImageBoardDpiSpinner = new javax.swing.JSpinner();
        diffImageUnchangedAlphaLabel = new javax.swing.JLabel();
        diffImageUnchangedAlphaSpinner = new javax.swing.JSpinner();
        diffImageAddedElementLabel = new javax.swing.JLabel();
        diffImageAddedElementTextField = new javax.swing.JTextField();
        diffImageAddedElementPanel = new javax.swing.JPanel();
        diffImageAddedElementButton = new javax.swing.JButton();
        diffImageRemovedElementLabel = new javax.swing.JLabel();
        diffImageRemovedElementTextField = new javax.swing.JTextField();
        diffImageRemovedElementPanel = new javax.swing.JPanel();
        diffImageRemovedElementButton = new javax.swing.JButton();
        diffImageUndefinedLabel = new javax.swing.JLabel();
        diffImageUndefinedTextField = new javax.swing.JTextField();
        diffImageUndefinedPanel = new javax.swing.JPanel();
        diffImageUndefinedButton = new javax.swing.JButton();
        diffImageSchematicDpiLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        eagleBinaryFileChooser.setDialogTitle("Select eagle binary ...");

        eaglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Eagle"));

        eagleBinaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eagleBinaryLabel.setText("Binary");

        eagleBinaryTextField.setEditable(false);

        eagleBinaryButton.setText("Select");
        eagleBinaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eagleBinaryButtonActionPerformed(evt);
            }
        });

        eagleSchematicBackgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eagleSchematicBackgroundLabel.setText("Schematic background");

        eagleSchematicBackgroundTextField.setEditable(false);

        eagleSchematicBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout eagleSchematicBackgroundPanelLayout = new javax.swing.GroupLayout(eagleSchematicBackgroundPanel);
        eagleSchematicBackgroundPanel.setLayout(eagleSchematicBackgroundPanelLayout);
        eagleSchematicBackgroundPanelLayout.setHorizontalGroup(
            eagleSchematicBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        eagleSchematicBackgroundPanelLayout.setVerticalGroup(
            eagleSchematicBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        eagleSchematicBackgroundButton.setText("Choose");
        eagleSchematicBackgroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eagleSchematicBackgroundButtonActionPerformed(evt);
            }
        });

        eagleBoardBackgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eagleBoardBackgroundLabel.setText("Board background");

        eagleBoardBackgroundTextField.setEditable(false);

        eagleBoardBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout eagleBoardBackgroundPanelLayout = new javax.swing.GroupLayout(eagleBoardBackgroundPanel);
        eagleBoardBackgroundPanel.setLayout(eagleBoardBackgroundPanelLayout);
        eagleBoardBackgroundPanelLayout.setHorizontalGroup(
            eagleBoardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        eagleBoardBackgroundPanelLayout.setVerticalGroup(
            eagleBoardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        eagleBoardBackgroundButton.setText("Choose");
        eagleBoardBackgroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eagleBoardBackgroundButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eaglePanelLayout = new javax.swing.GroupLayout(eaglePanel);
        eaglePanel.setLayout(eaglePanelLayout);
        eaglePanelLayout.setHorizontalGroup(
            eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eaglePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eaglePanelLayout.createSequentialGroup()
                        .addComponent(eagleBinaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eagleBinaryTextField))
                    .addGroup(eaglePanelLayout.createSequentialGroup()
                        .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eagleBoardBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eagleSchematicBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eaglePanelLayout.createSequentialGroup()
                                .addComponent(eagleSchematicBackgroundTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eagleSchematicBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(eaglePanelLayout.createSequentialGroup()
                                .addComponent(eagleBoardBackgroundTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eagleBoardBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eagleBoardBackgroundButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eagleSchematicBackgroundButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eagleBinaryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
        );
        eaglePanelLayout.setVerticalGroup(
            eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eaglePanelLayout.createSequentialGroup()
                .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eagleBinaryButton)
                    .addComponent(eagleBinaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eagleBinaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eagleSchematicBackgroundButton)
                    .addComponent(eagleSchematicBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eagleSchematicBackgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eagleSchematicBackgroundLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eagleBoardBackgroundButton)
                    .addComponent(eagleBoardBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(eaglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eagleBoardBackgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eagleBoardBackgroundLabel))))
        );

        diffImagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diff image"));

        diffImageBoardDpiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageBoardDpiLabel.setText("Board DPI");

        diffImageUnchangedAlphaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageUnchangedAlphaLabel.setText("Unchanged alpha");

        diffImageAddedElementLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageAddedElementLabel.setText("Added elements");

        diffImageAddedElementTextField.setEditable(false);

        diffImageAddedElementPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout diffImageAddedElementPanelLayout = new javax.swing.GroupLayout(diffImageAddedElementPanel);
        diffImageAddedElementPanel.setLayout(diffImageAddedElementPanelLayout);
        diffImageAddedElementPanelLayout.setHorizontalGroup(
            diffImageAddedElementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        diffImageAddedElementPanelLayout.setVerticalGroup(
            diffImageAddedElementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        diffImageAddedElementButton.setText("Choose");
        diffImageAddedElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffImageAddedElementButtonActionPerformed(evt);
            }
        });

        diffImageRemovedElementLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageRemovedElementLabel.setText("Removed elements");

        diffImageRemovedElementTextField.setEditable(false);

        diffImageRemovedElementPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout diffImageRemovedElementPanelLayout = new javax.swing.GroupLayout(diffImageRemovedElementPanel);
        diffImageRemovedElementPanel.setLayout(diffImageRemovedElementPanelLayout);
        diffImageRemovedElementPanelLayout.setHorizontalGroup(
            diffImageRemovedElementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        diffImageRemovedElementPanelLayout.setVerticalGroup(
            diffImageRemovedElementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        diffImageRemovedElementButton.setText("Choose");
        diffImageRemovedElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffImageRemovedElementButtonActionPerformed(evt);
            }
        });

        diffImageUndefinedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageUndefinedLabel.setText("Undefined");

        diffImageUndefinedTextField.setEditable(false);

        diffImageUndefinedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout diffImageUndefinedPanelLayout = new javax.swing.GroupLayout(diffImageUndefinedPanel);
        diffImageUndefinedPanel.setLayout(diffImageUndefinedPanelLayout);
        diffImageUndefinedPanelLayout.setHorizontalGroup(
            diffImageUndefinedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        diffImageUndefinedPanelLayout.setVerticalGroup(
            diffImageUndefinedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        diffImageUndefinedButton.setText("Choose");
        diffImageUndefinedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffImageUndefinedButtonActionPerformed(evt);
            }
        });

        diffImageSchematicDpiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        diffImageSchematicDpiLabel.setText("Schematic DPI");

        javax.swing.GroupLayout diffImagePanelLayout = new javax.swing.GroupLayout(diffImagePanel);
        diffImagePanel.setLayout(diffImagePanelLayout);
        diffImagePanelLayout.setHorizontalGroup(
            diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diffImagePanelLayout.createSequentialGroup()
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(diffImageRemovedElementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(diffImageAddedElementLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diffImageUnchangedAlphaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diffImageBoardDpiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diffImageUndefinedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diffImagePanelLayout.createSequentialGroup()
                        .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diffImageAddedElementTextField)
                            .addComponent(diffImageRemovedElementTextField)
                            .addComponent(diffImageUndefinedTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diffImageRemovedElementPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diffImageAddedElementPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diffImageUndefinedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diffImageAddedElementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(diffImageRemovedElementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diffImageUndefinedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(diffImageUnchangedAlphaSpinner)
                    .addComponent(diffImageBoardDpiSpinner, javax.swing.GroupLayout.Alignment.LEADING)))
            .addGroup(diffImagePanelLayout.createSequentialGroup()
                .addComponent(diffImageSchematicDpiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diffImageSchematicDpiSpinner))
        );
        diffImagePanelLayout.setVerticalGroup(
            diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diffImagePanelLayout.createSequentialGroup()
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diffImageSchematicDpiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diffImageSchematicDpiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diffImageBoardDpiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diffImageBoardDpiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diffImageUnchangedAlphaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diffImageUnchangedAlphaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diffImageAddedElementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diffImageAddedElementLabel))
                    .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(diffImageAddedElementButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(diffImageAddedElementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diffImageRemovedElementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diffImageRemovedElementButton)
                    .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diffImageRemovedElementLabel)
                        .addComponent(diffImageRemovedElementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diffImageUndefinedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diffImageUndefinedLabel)
                        .addComponent(diffImageUndefinedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(diffImageUndefinedButton)))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eaglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diffImagePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eaglePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diffImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eagleBinaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eagleBinaryButtonActionPerformed
        int returnVal = eagleBinaryFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File eagleBinary = eagleBinaryFileChooser.getSelectedFile();

            if (eagleBinary.exists()) {
                eagleBinaryTextField.setText(eagleBinaryFileChooser.getSelectedFile().toString());
            }
        }
    }//GEN-LAST:event_eagleBinaryButtonActionPerformed

    private void diffImageAddedElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffImageAddedElementButtonActionPerformed
        Color color
                = JColorChooser.showDialog(this,
                        "Choose color for added elements ...",
                        Color.decode(diffImageAddedElementTextField.getText()));

        if (color != null) {
            diffImageAddedElementTextField.setText("#" + Integer.toHexString(color.getRGB()).substring(2, 8));
            diffImageAddedElementPanel.setBackground(color);
        }
    }//GEN-LAST:event_diffImageAddedElementButtonActionPerformed

    private void diffImageUndefinedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffImageUndefinedButtonActionPerformed
        Color color = JColorChooser.showDialog(
                this,
                "Choose color for undedined ...",
                Color.decode(diffImageUndefinedTextField.getText()));

        if (color != null) {
            diffImageUndefinedTextField.setText("#" + Integer.toHexString(color.getRGB()).substring(2, 8));
            diffImageUndefinedPanel.setBackground(color);
        }
    }//GEN-LAST:event_diffImageUndefinedButtonActionPerformed

    private void diffImageRemovedElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffImageRemovedElementButtonActionPerformed
        Color color = JColorChooser.showDialog(
                this,
                "Choose color for removed elements ...",
                Color.decode(diffImageRemovedElementTextField.getText()));

        if (color != null) {
            diffImageRemovedElementTextField.setText("#" + Integer.toHexString(color.getRGB()).substring(2, 8));
            diffImageRemovedElementPanel.setBackground(color);
        }
    }//GEN-LAST:event_diffImageRemovedElementButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        options.save(
                eagleBinaryTextField.getText(),
                eagleSchematicBackgroundTextField.getText(),
                eagleBoardBackgroundTextField.getText(),
                diffImageSchematicDpiSpinner.getValue().toString(),
                diffImageBoardDpiSpinner.getValue().toString(),
                diffImageUnchangedAlphaSpinner.getValue().toString(),
                diffImageAddedElementTextField.getText(),
                diffImageRemovedElementTextField.getText(),
                diffImageUndefinedTextField.getText());

        close();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void eagleSchematicBackgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eagleSchematicBackgroundButtonActionPerformed
        Color color
                = JColorChooser.showDialog(this,
                        "Choose color for schematic background ...",
                        Color.decode(eagleSchematicBackgroundTextField.getText()));

        if (color != null) {
            eagleSchematicBackgroundTextField.setText("#" + Integer.toHexString(color.getRGB()).substring(2, 8));
            eagleSchematicBackgroundPanel.setBackground(color);
        }
    }//GEN-LAST:event_eagleSchematicBackgroundButtonActionPerformed

    private void eagleBoardBackgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eagleBoardBackgroundButtonActionPerformed
        Color color
                = JColorChooser.showDialog(this,
                        "Choose color for board background ...",
                        Color.decode(eagleBoardBackgroundTextField.getText()));

        if (color != null) {
            eagleBoardBackgroundTextField.setText("#" + Integer.toHexString(color.getRGB()).substring(2, 8));
            eagleBoardBackgroundPanel.setBackground(color);
        }
    }//GEN-LAST:event_eagleBoardBackgroundButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton diffImageAddedElementButton;
    private javax.swing.JLabel diffImageAddedElementLabel;
    private javax.swing.JPanel diffImageAddedElementPanel;
    private javax.swing.JTextField diffImageAddedElementTextField;
    private javax.swing.JLabel diffImageBoardDpiLabel;
    private javax.swing.JSpinner diffImageBoardDpiSpinner;
    private javax.swing.JPanel diffImagePanel;
    private javax.swing.JButton diffImageRemovedElementButton;
    private javax.swing.JLabel diffImageRemovedElementLabel;
    private javax.swing.JPanel diffImageRemovedElementPanel;
    private javax.swing.JTextField diffImageRemovedElementTextField;
    private javax.swing.JLabel diffImageSchematicDpiLabel;
    private javax.swing.JSpinner diffImageSchematicDpiSpinner;
    private javax.swing.JLabel diffImageUnchangedAlphaLabel;
    private javax.swing.JSpinner diffImageUnchangedAlphaSpinner;
    private javax.swing.JButton diffImageUndefinedButton;
    private javax.swing.JLabel diffImageUndefinedLabel;
    private javax.swing.JPanel diffImageUndefinedPanel;
    private javax.swing.JTextField diffImageUndefinedTextField;
    private javax.swing.JButton eagleBinaryButton;
    private javax.swing.JFileChooser eagleBinaryFileChooser;
    private javax.swing.JLabel eagleBinaryLabel;
    private javax.swing.JTextField eagleBinaryTextField;
    private javax.swing.JButton eagleBoardBackgroundButton;
    private javax.swing.JLabel eagleBoardBackgroundLabel;
    private javax.swing.JPanel eagleBoardBackgroundPanel;
    private javax.swing.JTextField eagleBoardBackgroundTextField;
    private javax.swing.JPanel eaglePanel;
    private javax.swing.JButton eagleSchematicBackgroundButton;
    private javax.swing.JLabel eagleSchematicBackgroundLabel;
    private javax.swing.JPanel eagleSchematicBackgroundPanel;
    private javax.swing.JTextField eagleSchematicBackgroundTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
