/*
 * The MIT License
 *
 * Copyright 2013 Andreas Giemza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package de.andreasgiemza.jgeagle;

import de.andreasgiemza.jgeagle.repo.data.EagleFile;
import de.andreasgiemza.jgeagle.gui.EagleFilesTree;
import de.andreasgiemza.jgeagle.gui.CommitsTables;
import de.andreasgiemza.jgeagle.gui.SheetsAndDiffImage;
import de.andreasgiemza.jgeagle.options.Options;
import de.andreasgiemza.jgeagle.repo.Repo;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.revwalk.RevCommit;

/**
 *
 * @author Andreas Giemza
 */
public class JGeagle extends javax.swing.JFrame {

    private final Options options;
    private final EagleFilesTree eagleFilesTree;
    private final CommitsTables commitsTables;
    private final SheetsAndDiffImage sheetsAndDiffImage;
    private Repo repo;

    /**
     * Creates new form JGeagle
     */
    public JGeagle() {
        initComponents();

        setLocation(new Double((Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2) - (this.getWidth() / 2)).intValue(),
                new Double((Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2) - (this.getHeight() / 2)).intValue());

        options = new Options();
        eagleFilesTree = new EagleFilesTree(this, eagleFilesJTree);
        commitsTables = new CommitsTables(this, oldCommitsTable, newCommitsTable);
        sheetsAndDiffImage = new SheetsAndDiffImage(
                options,
                sheetComboBox,
                sheetButton,
                diffImageButton);
    }

    public void eagleFileSelected(EagleFile eagleFile) {
        if (eagleFile == null) {
            commitsTables.reset();
            return;
        }

        try {
            repo.getEagleFileLogAndStatus(eagleFile);
            commitsTables.updateOldCommitsTable(eagleFile);
            commitsTables.resetNewCommitsTable();
            sheetsAndDiffImage.reset();
        } catch (IOException | GitAPIException ex) {
            Logger.getLogger(JGeagle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void oldCommitSelected(EagleFile eagleFile, RevCommit oldCommit) {
        commitsTables.updateNewCommitsTable(eagleFile, oldCommit);
        sheetsAndDiffImage.reset();
    }

    public void newCommitSelected(
            EagleFile eagleFile,
            RevCommit oldCommit,
            RevCommit newCommit) {
        options.cleanTempDir();

        if (eagleFile.getFileExtension().equals(EagleFile.BRD)) {
            sheetsAndDiffImage.brdSelected();
        } else {
            sheetsAndDiffImage.schSelected(repo, eagleFile, oldCommit, newCommit);
        }
    }

    private void openWebsite(String site) {
        try {
            java.awt.Desktop.getDesktop().browse(URI.create(site));
        } catch (IOException ex) {
            Logger.getLogger(JGeagle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repositoryFileChooser = new javax.swing.JFileChooser();
        eagleFilesPanel = new javax.swing.JPanel();
        eagleFilesScrollPane = new javax.swing.JScrollPane();
        eagleFilesJTree = new javax.swing.JTree();
        eagleFilesExpandAllButton = new javax.swing.JButton();
        eagleFilesCollapseAllButton = new javax.swing.JButton();
        commitsPanel = new javax.swing.JPanel();
        oldCommitsPanel = new javax.swing.JPanel();
        oldCommitsScrollPane = new javax.swing.JScrollPane();
        oldCommitsTable = new javax.swing.JTable();
        newCommitsPanel = new javax.swing.JPanel();
        newCommitsScrollPane = new javax.swing.JScrollPane();
        newCommitsTable = new javax.swing.JTable();
        variousPanel = new javax.swing.JPanel();
        sheetPanel = new javax.swing.JPanel();
        sheetButton = new javax.swing.JButton();
        sheetComboBox = new javax.swing.JComboBox();
        diffImagePanel = new javax.swing.JPanel();
        diffImageButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        repositoryMenu = new javax.swing.JMenu();
        repositoryMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        createImagesMenuItem = new javax.swing.JMenuItem();
        deleteImagesMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        preferencesMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        websiteMenuItem = new javax.swing.JMenuItem();
        githubMenuItem = new javax.swing.JMenuItem();
        helpSeparator = new javax.swing.JPopupMenu.Separator();
        aboutMenuItem = new javax.swing.JMenuItem();

        repositoryFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JGeagle");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("de/andreasgiemza/jgeagle/resources/jgeagle.png")));

        eagleFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Files"));

        eagleFilesJTree.setModel(null);
        eagleFilesScrollPane.setViewportView(eagleFilesJTree);

        eagleFilesExpandAllButton.setText("Expand all");
        eagleFilesExpandAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eagleFilesExpandAllButtonActionPerformed(evt);
            }
        });

        eagleFilesCollapseAllButton.setText("Collapse all");
        eagleFilesCollapseAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eagleFilesCollapseAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eagleFilesPanelLayout = new javax.swing.GroupLayout(eagleFilesPanel);
        eagleFilesPanel.setLayout(eagleFilesPanelLayout);
        eagleFilesPanelLayout.setHorizontalGroup(
            eagleFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eagleFilesPanelLayout.createSequentialGroup()
                .addComponent(eagleFilesScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eagleFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eagleFilesExpandAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eagleFilesCollapseAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
        );
        eagleFilesPanelLayout.setVerticalGroup(
            eagleFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eagleFilesPanelLayout.createSequentialGroup()
                .addComponent(eagleFilesExpandAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eagleFilesCollapseAllButton))
            .addComponent(eagleFilesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        commitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Commits"));
        commitsPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        oldCommitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Old"));
        oldCommitsPanel.setLayout(new javax.swing.BoxLayout(oldCommitsPanel, javax.swing.BoxLayout.LINE_AXIS));

        oldCommitsTable.setAutoCreateRowSorter(true);
        oldCommitsScrollPane.setViewportView(oldCommitsTable);

        oldCommitsPanel.add(oldCommitsScrollPane);

        commitsPanel.add(oldCommitsPanel);

        newCommitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New"));
        newCommitsPanel.setLayout(new javax.swing.BoxLayout(newCommitsPanel, javax.swing.BoxLayout.LINE_AXIS));

        newCommitsTable.setAutoCreateRowSorter(true);
        newCommitsScrollPane.setViewportView(newCommitsTable);

        newCommitsPanel.add(newCommitsScrollPane);

        commitsPanel.add(newCommitsPanel);

        variousPanel.setLayout(new java.awt.GridLayout(1, 0));

        sheetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sheet"));
        sheetPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        sheetButton.setText("Count");
        sheetButton.setEnabled(false);
        sheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheetButtonActionPerformed(evt);
            }
        });
        sheetPanel.add(sheetButton);

        sheetComboBox.setEnabled(false);
        sheetPanel.add(sheetComboBox);

        variousPanel.add(sheetPanel);

        diffImagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diff image"));

        diffImageButton.setText("Make and/or show");
        diffImageButton.setEnabled(false);
        diffImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diffImagePanelLayout = new javax.swing.GroupLayout(diffImagePanel);
        diffImagePanel.setLayout(diffImagePanelLayout);
        diffImagePanelLayout.setHorizontalGroup(
            diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diffImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        diffImagePanelLayout.setVerticalGroup(
            diffImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diffImageButton)
        );

        variousPanel.add(diffImagePanel);

        repositoryMenu.setText("Repository");

        repositoryMenuItem.setText("Open");
        repositoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repositoryMenuItemActionPerformed(evt);
            }
        });
        repositoryMenu.add(repositoryMenuItem);

        menuBar.add(repositoryMenu);

        toolsMenu.setText("Tools");

        createImagesMenuItem.setText("Create images");
        createImagesMenuItem.setEnabled(false);
        createImagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createImagesMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(createImagesMenuItem);

        deleteImagesMenuItem.setText("Delete images");
        deleteImagesMenuItem.setEnabled(false);
        toolsMenu.add(deleteImagesMenuItem);

        menuBar.add(toolsMenu);

        optionsMenu.setText("Options");

        preferencesMenuItem.setText("Preferences");
        preferencesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(preferencesMenuItem);

        menuBar.add(optionsMenu);

        helpMenu.setText("Help");

        websiteMenuItem.setText("Website (German)");
        websiteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(websiteMenuItem);

        githubMenuItem.setText("GitHub (English)");
        githubMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(githubMenuItem);
        helpMenu.add(helpSeparator);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eagleFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commitsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(variousPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eagleFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commitsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variousPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eagleFilesExpandAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eagleFilesExpandAllButtonActionPerformed
        eagleFilesTree.expandAll();
    }//GEN-LAST:event_eagleFilesExpandAllButtonActionPerformed

    private void eagleFilesCollapseAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eagleFilesCollapseAllButtonActionPerformed
        eagleFilesTree.collapseAll();
    }//GEN-LAST:event_eagleFilesCollapseAllButtonActionPerformed

    private void sheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sheetButtonActionPerformed
        sheetsAndDiffImage.countSheets(
                repo,
                commitsTables.getEagleFile(),
                commitsTables.getOldCommit(),
                commitsTables.getNewCommit());
    }//GEN-LAST:event_sheetButtonActionPerformed

    private void diffImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffImageButtonActionPerformed
        try {
            sheetsAndDiffImage.createDiffImage(
                    repo,
                    commitsTables.getEagleFile(),
                    commitsTables.getOldCommit(),
                    commitsTables.getNewCommit());
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(JGeagle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diffImageButtonActionPerformed

    private void websiteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteMenuItemActionPerformed
        openWebsite("http://www.andreasgiemza.de/jgeagle/");
    }//GEN-LAST:event_websiteMenuItemActionPerformed

    private void githubMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubMenuItemActionPerformed
        openWebsite("https://github.com/hurik/JGeagle");
    }//GEN-LAST:event_githubMenuItemActionPerformed

    private void repositoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repositoryMenuItemActionPerformed
        int returnVal = repositoryFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            eagleFilesTree.reset();
            commitsTables.reset();

            try {
                repo = new Repo(options, repositoryFileChooser.getSelectedFile().toPath());

                eagleFilesTree.buildAndDisplayTree(repo);

                createImagesMenuItem.setEnabled(true);
                deleteImagesMenuItem.setEnabled(true);
            } catch (IOException | GitAPIException ex) {
                Logger.getLogger(JGeagle.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_repositoryMenuItemActionPerformed

    private void preferencesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesMenuItemActionPerformed
        options.showPreferencesPanel(this);
    }//GEN-LAST:event_preferencesMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void createImagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createImagesMenuItemActionPerformed
        JDialog dialog = new JDialog(this, "Create images", true);
        //dialog.getContentPane().add(new CreateImagesPanel(options, jGit, eagleFiles));
        dialog.pack();
        dialog.setLocation(
                new Double((Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2) - (dialog.getWidth() / 2)).intValue(),
                new Double((Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2) - (dialog.getHeight() / 2)).intValue());
        dialog.setResizable(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_createImagesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGeagle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JGeagle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel commitsPanel;
    private javax.swing.JMenuItem createImagesMenuItem;
    private javax.swing.JMenuItem deleteImagesMenuItem;
    private javax.swing.JButton diffImageButton;
    private javax.swing.JPanel diffImagePanel;
    private javax.swing.JButton eagleFilesCollapseAllButton;
    private javax.swing.JButton eagleFilesExpandAllButton;
    private javax.swing.JTree eagleFilesJTree;
    private javax.swing.JPanel eagleFilesPanel;
    private javax.swing.JScrollPane eagleFilesScrollPane;
    private javax.swing.JMenuItem githubMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator helpSeparator;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel newCommitsPanel;
    private javax.swing.JScrollPane newCommitsScrollPane;
    private javax.swing.JTable newCommitsTable;
    private javax.swing.JPanel oldCommitsPanel;
    private javax.swing.JScrollPane oldCommitsScrollPane;
    private javax.swing.JTable oldCommitsTable;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JFileChooser repositoryFileChooser;
    private javax.swing.JMenu repositoryMenu;
    private javax.swing.JMenuItem repositoryMenuItem;
    private javax.swing.JButton sheetButton;
    private javax.swing.JComboBox sheetComboBox;
    private javax.swing.JPanel sheetPanel;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JPanel variousPanel;
    private javax.swing.JMenuItem websiteMenuItem;
    // End of variables declaration//GEN-END:variables
}
